version: "3.4"

services:
  mssql:
    container_name: mssql
    image: mcr.microsoft.com/mssql/server
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Password@123
      - MSSQL_PID=Developer

  # redis:
  #   container_name: redis
  #   image: redis
  #   ports:
  #     - "6379:6379"

  # DB
  create_db_poc_test:
    image: mcr.microsoft.com/mssql-tools
    depends_on:
      - mssql
    command: /bin/bash -c 'until /opt/mssql-tools/bin/sqlcmd -S mssql -U sa -P "Password@123" -Q "create database [poc-test]"; do sleep 5; done'

  flyway_authorizer_mastercard:
    image: flyway/flyway
    command: migrate
    depends_on:
      - mssql
      - create_db_poc_test
    volumes:
      - ./sql:/flyway/sql
      - ./conf:/flyway/conf