version: "3.4"

services:
  mssql:
    container_name: mssql
    image: mcr.microsoft.com/mssql/server
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Password@123
      - MSSQL_PID=Developer

  # redis:
  #   container_name: redis
  #   image: redis
  #   ports:
  #     - "6379:6379"

  # DB